### ISSUE TITLE
check_redfish.py  fails --nic if nic-model is "82599"

### ISSUE THREAD

**Issue by dan-m-joh** [bb-Ricardo/check_redfish#21]
When running "check_redfish.py -H <host> -u <user> -p <passwd> --nic -d"
the script exits with the following output:
```
Traceback (most recent call last):
  File "./check_redfish.py", line 201, in <module>
    if any(x in args.requested_query for x in ['nic', 'all']):      get_network_interfaces(plugin)
  File "/mnt/data01/contrib_plugins/check_redfish/cr_module/nic.py", line 23, in get_network_interfaces
    get_system_nics(plugin_object, system)
  File "/mnt/data01/contrib_plugins/check_redfish/cr_module/nic.py", line 528, in get_system_nics
    if len(network_adapter.model or '') > len(network_adapter.name or '') else network_adapter.name
TypeError: object of type 'int' has no len()

```
I have narrowed it down to that in our case "network_adapter.model" is 82599 (Huawei Hardware).
Adding "str()" around "network_adapter.model" and "network_adapter.name" in nic.py at line 528 solves the issue for me.

Regards,
D/\N

**Comment by bb-Ricardo** [comment]
thank you
