### ISSUE TITLE
Unable to get the NIC Status

### ISSUE THREAD

**Issue by robse030** [bb-Ricardo/check_redfish#70]
Hi, i'am unable to get the status about the NICs from my DELL-Server. 

Here is the output:

Traceback (most recent call last):
File "/usr/lib/nagios/plugins/check_redfish/check_redfish.py", line 162, in if any(x in args.requested_query for x in ['nic', 'all']): get_network_interfaces(plugin) File "/opt/plugins/check_redfish/cr_module/nic.py", line 23, in get_network_interfaces get_system_nics(plugin_object, system) File "/opt/plugins/check_redfish/cr_module/nic.py", line 388, in get_system_nics port_inventory_data = get_network_function(network_function) File "/opt/plugins/check_redfish/cr_module/nic.py", line 206, in get_network_function port_inventory = get_network_port(physical_port_path, network_function_id, True) File "/opt/plugins/check_redfish/cr_module/nic.py", line 147, in get_network_port addresses=format_interface_addresses(grab(port_response, "AssociatedNetworkAddresses")), File "/opt/plugins/check_redfish/cr_module/nic.py", line 62, in format_interface_addresses address = address.upper() AttributeError: 'NoneType' object has no attribute 'upper'

Kind regards,
robert

**Comment by bb-Ricardo** [comment]
Hi,

Thanks for the issue. It looks like an easy fix. Will have a look at it today or tomorrow.

**Comment by bb-Ricardo** [comment]
Hey, can you please test the "next-release" branch? Thank you.

**Comment by robse030** [comment]
Perfect, now i get the status again. :)
Thank you

**Comment by bb-Ricardo** [comment]
Wow, this was quick. Thank you for testing.
