### ISSUE TITLE
Add support for Lenovo SR650 V2

### ISSUE THREAD

**Issue by matejzero** [bb-Ricardo/check_redfish#77]
Hello,

I just got a new SR650 V2 on test and tried the check as we are already running a bunch of Lenovo servers with this check.

Most of the checks work.

`--nic` is failing:
> [UNKNOWN]: Request error: No network_adapter data returned for API URL '/redfish/v1/Chassis/1/NetworkAdapters/slot-9', No network adapter or interface data returned for API URL '/redfish/v1/Systems/1/NetworkInterfaces'

`--mel` is failing:
> Traceback (most recent call last):
  File "./check_redfish/check_redfish.py", line 167, in <module>
    if any(x in args.requested_query for x in ['mel', 'all']):      get_event_log(plugin, "Manager")
  File "/usr/lib64/nagios/3rd_party_plugins/check_redfish/cr_module/event.py", line 140, in get_event_log
    get_event_log_generic(plugin_object, event_type, event_entries_redfish_path)
  File "/usr/lib64/nagios/3rd_party_plugins/check_redfish/cr_module/event.py", line 253, in get_event_log_generic
    if len(event_entries) == 0:
TypeError: object of type 'NoneType' has no len()

I have created a RedFish mockup if you need it. I will have to return the server on Monday, but I might get a few of them in the coming months and support for this would be welcome.

FYI, your check is also working on Lenovo SR630, SR650, SR645, SR665 (I have many of them in production). I think it works on SR635 and SR655 as well, but remote management in them is massively underpowered and basic --proc takes 40s+. Running `-all` will timeout in 5m.

**Comment by bb-Ricardo** [comment]
Hi,

ui, this looks not so nice.

And of course I would be interested in a MockUp. 😁

Just sent it over and I gonna have a look.

And thanks for other Lenovo Server Models, I will add them to the list.

**Comment by bb-Ricardo** [comment]
Ping. Would still be interested in the MockUp.

**Comment by matejzero** [comment]
Mock up sent.

**Comment by bb-Ricardo** [comment]
thank you, got it. Will have a look at it.

**Comment by bb-Ricardo** [comment]
Hi,

so I had a look around the MockUp for the network interface issue.
It seems there is still a bug in the xClarity BMC Firmware.

Network interfaces are defined under `/redfish/v1/Systems/1/NetworkInterfaces`.
Here we can only find one adapter even though this system has two.
```json
{
    "Members@odata.count": 1,
    "Name": "NetworkInterfaceCollection",
    "@odata.etag": "\"ABC\"",
    "@odata.id": "/redfish/v1/Systems/1/NetworkInterfaces",
    "Description": "A collection of NetworkInterface resource instances.",
    "Members": [
        {
            "@odata.id": "/redfish/v1/Systems/1/NetworkInterfaces/1"
        }
    ],
    "@odata.type": "#NetworkInterfaceCollection.NetworkInterfaceCollection"
}
```
Then looking into `/redfish/v1/Systems/1/NetworkInterfaces/1` reveals following output:
```json
{
    "Id": "1",
    "Name": "Network Interface 1",
    "@odata.type": "#NetworkInterface.v1_1_3.NetworkInterface",
    "@odata.id": "/redfish/v1/Systems/1/NetworkInterfaces/1",
    "Status": {
        "Health": "OK",
        "State": "Enabled"
    },
    "NetworkDeviceFunctions": {
        "@odata.id": "/redfish/v1/Chassis/1/NetworkAdapters/slot-9/NetworkDeviceFunctions"
    },
    "NetworkPorts": {
        "@odata.id": "/redfish/v1/Chassis/1/NetworkAdapters/slot-9/NetworkPorts"
    },
    "Description": "A NetworkInterface contains references linking NetworkAdapter, NetworkPort, and NetworkDeviceFunction resources and represents the functionality available to the containing system.",
    "Links": {
        "NetworkAdapter": {
            "@odata.id": "/redfish/v1/Chassis/1/NetworkAdapters/slot-9"
        }
    },
    "@odata.etag": "\"516f50498514266e1ea\""
}
```
This points us to `/redfish/v1/Chassis/1/NetworkAdapters/slot-9` but this path **DOES NOT EXISTS**.

Looking at `/redfish/v1/Chassis/1/NetworkAdapters/` we get:
```json
{
    "Members@odata.count": 2,
    "Members": [
        {
            "@odata.id": "/redfish/v1/Chassis/1/NetworkAdapters/slot-9.Bus_23.Dev_0"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/1/NetworkAdapters/slot-9.Bus_24.Dev_0"
        }
    ],
    "@odata.type": "#NetworkAdapterCollection.NetworkAdapterCollection",
    "@odata.id": "/redfish/v1/Chassis/1/NetworkAdapters",
    "Name": "NetworkAdapterCollection",
    "Description": "A collection of NetworkAdapter resource instances.",
    "@odata.etag": "\"ABC\""
}
```

So instead of `slot-9` it should point to `slot-9.Bus_23.Dev_0` 🤷 

After fixing these errors manually I get:
```
[OK]: All network adapter (2) and ports (4) are in good condition
[OK]: Adapter Broadcom 5720 1GbE 2-port OCP Ethernet Adapter (FW: 219.0.144.0) status: OK
[OK]: Port slot-9.Bus_23.Dev_0.1 (type: Ethernet, speed: None, autoneg: None, duplex: None) status: OK, link: None
[OK]: Port slot-9.Bus_23.Dev_0.2 (type: Ethernet, speed: None, autoneg: None, duplex: None) status: OK, link: None
[OK]: Adapter Broadcom 57416 10GBASE-T 2-port OCP Ethernet Adapter (FW: 219.0.144.0) status: OK
[OK]: Port slot-9.Bus_24.Dev_0.1 (type: Ethernet, speed: None, autoneg: None, duplex: None) status: OK, link: None
[OK]: Port slot-9.Bus_24.Dev_0.2 (type: Ethernet, speed: None, autoneg: None, duplex: None) status: OK, link: None
```
Which is not very helpful either.

**Comment by bb-Ricardo** [comment]
Regarding the log services:

The locations of the log entries have changed.
Lenovo SR650 `/redfish/v1/Systems/1/LogServices/`:
```json
{
    "@odata.id": "/redfish/v1/Systems/1/LogServices/",
    "Members@odata.count": 2,
    "@odata.context": "/redfish/v1/$metadata#LogServiceCollection.LogServiceCollection",
    "Members": [
        {
            "@odata.id": "/redfish/v1/Systems/1/LogServices/StandardLog/"
        },
        {
            "@odata.id": "/redfish/v1/Systems/1/LogServices/ActiveLog/"
        }
    ],
    "@odata.type": "#LogServiceCollection.LogServiceCollection",
    "Members@odata.navigationLink": "/redfish/v1/Systems/1/LogServices/Members",
    "@odata.etag": "W/\"f6c7f109515ebbe145ce4ce7918202b4\"",
    "Name": "LogServiceCollection",
    "Description": "A Collection of LogService resource instances."
}
```

Lenovo SR650V2 `/redfish/v1/Systems/1/LogServices/`:
```json
{
    "Members@odata.count": 5,
    "Members": [
        {
            "@odata.id": "/redfish/v1/Systems/1/LogServices/PlatformLog"
        },
        {
            "@odata.id": "/redfish/v1/Systems/1/LogServices/AuditLog"
        },
        {
            "@odata.id": "/redfish/v1/Systems/1/LogServices/ActiveLog"
        },
        {
            "@odata.id": "/redfish/v1/Systems/1/LogServices/MaintenanceLog"
        },
        {
            "@odata.id": "/redfish/v1/Systems/1/LogServices/SaLog"
        }
    ],
    "@odata.type": "#LogServiceCollection.LogServiceCollection",
    "@odata.id": "/redfish/v1/Systems/1/LogServices",
    "Name": "LogServiceCollection",
    "Description": "A collection of LogService resource instances.",
    "@odata.etag": "\"ABC\""
}
```

and current Code looks like this
https://github.com/bb-Ricardo/check_redfish/blob/5265e955c742d336b674f821dfc83c6dcf140930/cr_module/classes/vendor.py#L93-L103

And I can't just change it as it would break support for older systems.
So I have to come up with a new way of defining loc locations. Also a distinction between 'system event logs' and 'manager event logs' doesn't seem so clear anymore. 🤔

**Comment by bb-Ricardo** [comment]
> `--mel` is failing:
> 
> ```python
> Traceback (most recent call last):
>   File "./check_redfish/check_redfish.py", line 167, in <module>
>     if any(x in args.requested_query for x in ['mel', 'all']):      get_event_log(plugin, "Manager")
>   File "/usr/lib64/nagios/3rd_party_plugins/check_redfish/cr_module/event.py", line 140, in get_event_log
>     get_event_log_generic(plugin_object, event_type, event_entries_redfish_path)
>   File "/usr/lib64/nagios/3rd_party_plugins/check_redfish/cr_module/event.py", line 253, in get_event_log_generic
>     if len(event_entries) == 0:
> TypeError: object of type 'NoneType' has no len()
> ```

It seems you are using an older plugin version. This issue has been fixed already. Can you update your plugin and check if this issue still persist?

Thank you

**Comment by matejzero** [comment]
Regarding the network interfaces, I think this is a special case as this server has a special combo card in OCP slot. I think the output should be correct if one only has a single card in the slot (either Xx10G or Xx1GBit). This server has 2 cards in the same slot: `ThinkSystem Broadcom 57416 10GBASE-T 2-port + 5720 1GbE 2-port OCP Ethernet Adapter`. This is the only combo card and I'm not sure how common that configuration is. I never came across it until todat tbh.

Regarding the MEL output, I was sure I was using the latest version, but it turns out I wasn't. I'm sorry for that.

I had to return the server to the vendor and can't try updating the firmware version to see if this changes in newer versions (server same straight from the box, so it might be running an outdated firmware). I will also try and update one of my SR630/SR650 servers with latest firmware to see if they changed log location there as well. If they did, then we can continue to work on this and find a solution. If not, we will have to wait until we get a SR650V2.

**Comment by matejzero** [comment]
I can confirm latest firmware for SR630/SR650 (UXSP 2.60) is working with 1.2.0 and 1.3.2 version of this check. So I guess Log services changed only for V2 servers.

So, as far as NICs go, this is a special case and not sure if fix is needed. At least not for my use as we will use different cards.

As far as logs go, I don'r have a good idea for a solution. Maybe we can close the ticket and I'll reopen it when/if we get some V2 servers and then try to come up with a better idea for logs?

**Comment by bb-Ricardo** [comment]
Added Support for new logs in 'next-release' branch.

Do you have some SR650V2 servers where you could test it?

**Comment by matejzero** [comment]
Hey,

we are still waiting for procurement to come through, so I don't have a server yet. ETA is 2-3 months:/ You can close this and I will test it as soon as I get the server.
