### ISSUE TITLE
Issues with empty members list on idrac5

### ISSUE THREAD

**Issue by silenius** [bb-Ricardo/check_redfish#86]
Hello,

I just upgraded from IDRAC4 to IDRAC5 on a small r340 server and from time to time I'm getting the following error:

```
PROBLEM troubadour.lan/HW Management Log is WARNING - Traceback (most recent call last):
  File "/usr/local/libexec/nagios/check_redfish/check_redfish.py", line 167, in <module>
    if any(x in args.requested_query for x in ['mel', 'all']):      get_event_log(plugin, "Manager")
  File "/usr/local/libexec/nagios/check_redfish/cr_module/event.py", line 140, in get_event_log
    get_event_log_generic(plugin_object, event_type, event_entries_redfish_path)
  File "/usr/local/libexec/nagios/check_redfish/cr_module/event.py", line 251, in get_event_log_generic
    event_entries = plugin_object.rf.get(redfish_path, max_members=max_entries).get("Members")
  File "/usr/local/libexec/nagios/check_redfish/cr_module/classes/redfish.py", line 406, in get
    if len(this_response.get("Members")) == 0:
TypeError: object of type 'NoneType' has no len()
```

it looks like some issue in the management log

**Comment by bb-Ricardo** [comment]
Hi,

can you try the latest development branch?

**Comment by bb-Ricardo** [comment]
fixed now in "next-release" branch and will be in release "1.4.0"
